export const WORDS = [
  {
    id: "dom-czesc",
    polish: "cześć",
    russian: "привет",
    topic: "Знакомство",
    level: "A1",
    example: "Cześć, miło cię widzieć.",
  },
  {
    id: "dom-dziekuje",
    polish: "dziękuję",
    russian: "спасибо",
    topic: "Знакомство",
    level: "A1",
    example: "Dziękuję za pomoc.",
  },
  {
    id: "dom-prosze",
    polish: "proszę",
    russian: "пожалуйста",
    topic: "Знакомство",
    level: "A1",
    example: "Proszę, usiądź tutaj.",
  },
  {
    id: "znakomstwo-imie",
    polish: "jak masz na imię",
    russian: "как тебя зовут",
    topic: "Знакомство",
    level: "A1",
    example: "Cześć, jak masz na imię?",
  },
  {
    id: "znakomstwo-milo",
    polish: "miło mi",
    russian: "приятно познакомиться",
    topic: "Знакомство",
    level: "A1",
    example: "Miło mi cię poznać.",
  },
  {
    id: "znakomstwo-skad",
    polish: "skąd jesteś",
    russian: "откуда ты",
    topic: "Знакомство",
    level: "A1",
    example: "Skąd jesteś? Jestem z Ukrainy.",
  },
  {
    id: "kawiarnia-kawa",
    polish: "kawa",
    russian: "кофе",
    topic: "Кафе",
    level: "A1",
    example: "Poproszę dużą kawę.",
  },
  {
    id: "kawiarnia-herbata",
    polish: "herbata",
    russian: "чай",
    topic: "Кафе",
    level: "A1",
    example: "Lubię zieloną herbatę.",
  },
  {
    id: "kawiarnia-ciasto",
    polish: "ciasto",
    russian: "пирог",
    topic: "Кафе",
    level: "A1",
    example: "Poproszę kawałek ciasta.",
  },
  {
    id: "kawiarnia-cukier",
    polish: "cukier",
    russian: "сахар",
    topic: "Кафе",
    level: "A1",
    example: "Do kawy biorę trochę cukru.",
  },
  {
    id: "kawiarnia-woda",
    polish: "woda",
    russian: "вода",
    topic: "Кафе",
    level: "A1",
    example: "Czy mogę dostać wodę?",
  },
  {
    id: "kawiarnia-rachunek",
    polish: "rachunek",
    russian: "счет",
    topic: "Кафе",
    level: "A1",
    example: "Poproszę rachunek.",
  },
  {
    id: "zakupy-sklep",
    polish: "sklep",
    russian: "магазин",
    topic: "Покупки",
    level: "A1",
    example: "Ten sklep jest blisko domu.",
  },
  {
    id: "zakupy-cena",
    polish: "cena",
    russian: "цена",
    topic: "Покупки",
    level: "A1",
    example: "Jaka jest cena tej książki?",
  },
  {
    id: "zakupy-chleb",
    polish: "chleb",
    russian: "хлеб",
    topic: "Покупки",
    level: "A1",
    example: "Kupuję świeży chleb.",
  },
  {
    id: "zakupy-mleko",
    polish: "mleko",
    russian: "молоко",
    topic: "Покупки",
    level: "A1",
    example: "Potrzebuję jednego litra mleka.",
  },
  {
    id: "zakupy-owoc",
    polish: "owoc",
    russian: "фрукт",
    topic: "Покупки",
    level: "A1",
    example: "Ten owoc jest bardzo słodki.",
  },
  {
    id: "zakupy-koszyk",
    polish: "koszyk",
    russian: "корзина",
    topic: "Покупки",
    level: "A1",
    example: "Mam pełny koszyk zakupów.",
  },
  {
    id: "miasto-droga",
    polish: "droga",
    russian: "дорога",
    topic: "Город",
    level: "A1",
    example: "To jest długa droga do szkoły.",
  },
  {
    id: "miasto-dworzec",
    polish: "dworzec",
    russian: "вокзал",
    topic: "Город",
    level: "A1",
    example: "Dworzec jest po lewej stronie.",
  },
  {
    id: "miasto-ulica",
    polish: "ulica",
    russian: "улица",
    topic: "Город",
    level: "A1",
    example: "Ta ulica jest bardzo długa.",
  },
  {
    id: "miasto-przystanek",
    polish: "przystanek",
    russian: "остановка",
    topic: "Город",
    level: "A1",
    example: "Przystanek jest obok szkoły.",
  },
  {
    id: "miasto-autobus",
    polish: "autobus",
    russian: "автобус",
    topic: "Город",
    level: "A1",
    example: "Autobus jedzie do centrum.",
  },
  {
    id: "miasto-centrum",
    polish: "centrum",
    russian: "центр",
    topic: "Город",
    level: "A1",
    example: "Mieszkam blisko centrum.",
  },
  {
    id: "codzienne-rano",
    polish: "rano",
    russian: "утром",
    topic: "Быт",
    level: "A1",
    example: "Rano piję kawę i czytam.",
  },
  {
    id: "codzienne-wieczor",
    polish: "wieczór",
    russian: "вечер",
    topic: "Быт",
    level: "A1",
    example: "Wieczór spędzam z rodziną.",
  },
  {
    id: "dom-rodzina",
    polish: "rodzina",
    russian: "семья",
    topic: "Быт",
    level: "A1",
    example: "Moja rodzina mieszka w Warszawie.",
  },
  {
    id: "dom-dom",
    polish: "dom",
    russian: "дом",
    topic: "Быт",
    level: "A1",
    example: "Wracam do domu wieczorem.",
  },
  {
    id: "dom-praca",
    polish: "praca",
    russian: "работа",
    topic: "Быт",
    level: "A1",
    example: "Mam dużo pracy dzisiaj.",
  },
  {
    id: "byt-sniadanie",
    polish: "śniadanie",
    russian: "завтрак",
    topic: "Быт",
    level: "A1",
    example: "Jem śniadanie rano.",
  },
  {
    id: "byt-kolacja",
    polish: "kolacja",
    russian: "ужин",
    topic: "Быт",
    level: "A1",
    example: "Kolację jem z rodziną.",
  },
  {
    id: "byt-szkola",
    polish: "szkoła",
    russian: "школа",
    topic: "Быт",
    level: "A1",
    example: "Szkoła jest blisko domu.",
  },
  {
    id: "czas-dzisiaj",
    polish: "dzisiaj",
    russian: "сегодня",
    topic: "Время",
    level: "A1",
    example: "Dzisiaj mam lekcję polskiego.",
  },
  {
    id: "czas-jutro",
    polish: "jutro",
    russian: "завтра",
    topic: "Время",
    level: "A1",
    example: "Jutro idę do sklepu.",
  },
  {
    id: "czas-wczoraj",
    polish: "wczoraj",
    russian: "вчера",
    topic: "Время",
    level: "A1",
    example: "Wczoraj padał deszcz.",
  },
  {
    id: "czas-teraz",
    polish: "teraz",
    russian: "сейчас",
    topic: "Время",
    level: "A1",
    example: "Teraz uczę się polskiego.",
  },
  {
    id: "czas-pozniej",
    polish: "później",
    russian: "позже",
    topic: "Время",
    level: "A1",
    example: "Porozmawiamy później.",
  },
  {
    id: "czas-godzina",
    polish: "godzina",
    russian: "час",
    topic: "Время",
    level: "A1",
    example: "Która jest godzina?",
  },
];
